# CodingCoffee  OpenBMC Robotframework  GitPod Examples more courses : http://www.codingcoffee.org
tasks:
  - init: echo 'this is OpenBMC Robotframework hello gitpod example' # runs during prebuild
    command: pip install robotframework  && pip install -U requests  && pip install -U robotframework-requests && pip install -U robotframework-httplibrary && pip install redfish && pip install robotframework-sshlibrary && pip install robotframework-scplibrary && pip install -r requirements.txt && pip install -U tox && sudo apt-get install expect

# CodingCoffee  C/C++ GitPod Examples more courses : http://www.codingcoffee.org
ports:
  - port: 3000
    onOpen: open-preview
